# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/CHINNA/Vivado_workspace/cnn_accelerator/cnn_accelerator.srcs/sources_1/bd/cnn_pipeline/ip/cnn_pipeline_fifo_generator_0_0/cnn_pipeline_fifo_generator_0_0.xci
# IP: The module: 'cnn_pipeline_fifo_generator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/CHINNA/Vivado_workspace/cnn_accelerator/cnn_accelerator.gen/sources_1/bd/cnn_pipeline/ip/cnn_pipeline_fifo_generator_0_0/cnn_pipeline_fifo_generator_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnn_pipeline_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/CHINNA/Vivado_workspace/cnn_accelerator/cnn_accelerator.gen/sources_1/bd/cnn_pipeline/ip/cnn_pipeline_fifo_generator_0_0/cnn_pipeline_fifo_generator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnn_pipeline_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/CHINNA/Vivado_workspace/cnn_accelerator/cnn_accelerator.srcs/sources_1/bd/cnn_pipeline/ip/cnn_pipeline_fifo_generator_0_0/cnn_pipeline_fifo_generator_0_0.xci
# IP: The module: 'cnn_pipeline_fifo_generator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/CHINNA/Vivado_workspace/cnn_accelerator/cnn_accelerator.gen/sources_1/bd/cnn_pipeline/ip/cnn_pipeline_fifo_generator_0_0/cnn_pipeline_fifo_generator_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnn_pipeline_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/CHINNA/Vivado_workspace/cnn_accelerator/cnn_accelerator.gen/sources_1/bd/cnn_pipeline/ip/cnn_pipeline_fifo_generator_0_0/cnn_pipeline_fifo_generator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnn_pipeline_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
