// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="maxpool_maxpool,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.269000,HLS_SYN_LAT=37,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=447,HLS_SYN_LUT=882,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module maxpool (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [1:0] in_stream_TKEEP;
input  [1:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [15:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [1:0] out_stream_TKEEP;
output  [1:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_start;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_done;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_idle;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_ready;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_in_stream_TREADY;
wire   [15:0] grp_maxpool_Pipeline_READ_INPUT_fu_132_input_15_out;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_input_15_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_READ_INPUT_fu_132_input_14_out;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_input_14_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_READ_INPUT_fu_132_input_13_out;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_input_13_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_READ_INPUT_fu_132_input_12_out;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_input_12_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_READ_INPUT_fu_132_input_11_out;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_input_11_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_READ_INPUT_fu_132_input_10_out;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_input_10_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_READ_INPUT_fu_132_input_9_out;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_input_9_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_READ_INPUT_fu_132_input_8_out;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_input_8_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_READ_INPUT_fu_132_input_7_out;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_input_7_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_READ_INPUT_fu_132_input_6_out;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_input_6_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_READ_INPUT_fu_132_input_5_out;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_input_5_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_READ_INPUT_fu_132_input_4_out;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_input_4_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_READ_INPUT_fu_132_input_3_out;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_input_3_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_READ_INPUT_fu_132_input_2_out;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_input_2_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_READ_INPUT_fu_132_input_1_out;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_input_1_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_READ_INPUT_fu_132_input_out;
wire    grp_maxpool_Pipeline_READ_INPUT_fu_132_input_out_ap_vld;
wire    grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_start;
wire    grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_done;
wire    grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_idle;
wire    grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_ready;
wire   [15:0] grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_3_out;
wire    grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_3_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_2_out;
wire    grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_2_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_1_out;
wire    grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_1_out_ap_vld;
wire   [15:0] grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_out;
wire    grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_out_ap_vld;
wire    grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_start;
wire    grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_done;
wire    grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_idle;
wire    grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_ready;
wire    grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TREADY;
wire   [15:0] grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TDATA;
wire    grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TVALID;
wire   [1:0] grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TKEEP;
wire   [1:0] grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TSTRB;
wire   [0:0] grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TLAST;
reg    grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg   [15:0] out_stream_TDATA_reg;
reg   [1:0] out_stream_TKEEP_reg;
reg   [1:0] out_stream_TSTRB_reg;
reg   [0:0] out_stream_TLAST_reg;
wire    ap_CS_fsm_state8;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [15:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [1:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [1:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
reg   [15:0] out_stream_TDATA_int_regslice;
wire    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
reg   [1:0] out_stream_TKEEP_int_regslice;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
reg   [1:0] out_stream_TSTRB_int_regslice;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
reg   [0:0] out_stream_TLAST_int_regslice;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_start_reg = 1'b0;
#0 grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_start_reg = 1'b0;
#0 grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_start_reg = 1'b0;
end

maxpool_maxpool_Pipeline_READ_INPUT grp_maxpool_Pipeline_READ_INPUT_fu_132(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_start),
    .ap_done(grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_done),
    .ap_idle(grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_idle),
    .ap_ready(grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_maxpool_Pipeline_READ_INPUT_fu_132_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice),
    .input_15_out(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_15_out),
    .input_15_out_ap_vld(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_15_out_ap_vld),
    .input_14_out(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_14_out),
    .input_14_out_ap_vld(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_14_out_ap_vld),
    .input_13_out(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_13_out),
    .input_13_out_ap_vld(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_13_out_ap_vld),
    .input_12_out(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_12_out),
    .input_12_out_ap_vld(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_12_out_ap_vld),
    .input_11_out(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_11_out),
    .input_11_out_ap_vld(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_11_out_ap_vld),
    .input_10_out(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_10_out),
    .input_10_out_ap_vld(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_10_out_ap_vld),
    .input_9_out(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_9_out),
    .input_9_out_ap_vld(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_9_out_ap_vld),
    .input_8_out(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_8_out),
    .input_8_out_ap_vld(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_8_out_ap_vld),
    .input_7_out(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_7_out),
    .input_7_out_ap_vld(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_7_out_ap_vld),
    .input_6_out(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_6_out),
    .input_6_out_ap_vld(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_6_out_ap_vld),
    .input_5_out(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_5_out),
    .input_5_out_ap_vld(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_5_out_ap_vld),
    .input_4_out(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_4_out),
    .input_4_out_ap_vld(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_4_out_ap_vld),
    .input_3_out(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_3_out),
    .input_3_out_ap_vld(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_3_out_ap_vld),
    .input_2_out(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_2_out),
    .input_2_out_ap_vld(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_2_out_ap_vld),
    .input_1_out(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_1_out),
    .input_1_out_ap_vld(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_1_out_ap_vld),
    .input_out(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_out),
    .input_out_ap_vld(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_out_ap_vld)
);

maxpool_maxpool_Pipeline_POOL_OR_POOL_OC grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_start),
    .ap_done(grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_done),
    .ap_idle(grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_idle),
    .ap_ready(grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_ready),
    .input_2_reload(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_2_out),
    .input_reload(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_out),
    .input_10_reload(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_10_out),
    .input_8_reload(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_8_out),
    .input_3_reload(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_3_out),
    .input_1_reload(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_1_out),
    .input_11_reload(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_11_out),
    .input_9_reload(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_9_out),
    .input_6_reload(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_6_out),
    .input_4_reload(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_4_out),
    .input_14_reload(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_14_out),
    .input_12_reload(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_12_out),
    .input_7_reload(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_7_out),
    .input_5_reload(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_5_out),
    .input_15_reload(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_15_out),
    .input_13_reload(grp_maxpool_Pipeline_READ_INPUT_fu_132_input_13_out),
    .output_3_out(grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_3_out),
    .output_3_out_ap_vld(grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_3_out_ap_vld),
    .output_2_out(grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_2_out),
    .output_2_out_ap_vld(grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_2_out_ap_vld),
    .output_1_out(grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_1_out),
    .output_1_out_ap_vld(grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_1_out_ap_vld),
    .output_out(grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_out),
    .output_out_ap_vld(grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_out_ap_vld)
);

maxpool_maxpool_Pipeline_WRITE_OUTPUT grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_start),
    .ap_done(grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_done),
    .ap_idle(grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_idle),
    .ap_ready(grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_ready),
    .out_stream_TREADY(grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TREADY),
    .output_1_reload(grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_1_out),
    .output_reload(grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_out),
    .output_3_reload(grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_3_out),
    .output_2_reload(grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_output_2_out),
    .out_stream_TDATA(grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TDATA),
    .out_stream_TVALID(grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TVALID),
    .out_stream_TKEEP(grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TKEEP),
    .out_stream_TSTRB(grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TSTRB),
    .out_stream_TLAST(grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TLAST)
);

maxpool_regslice_both #(
    .DataWidth( 16 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

maxpool_regslice_both #(
    .DataWidth( 2 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

maxpool_regslice_both #(
    .DataWidth( 2 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

maxpool_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

maxpool_regslice_both #(
    .DataWidth( 16 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TVALID),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

maxpool_regslice_both #(
    .DataWidth( 2 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TKEEP_int_regslice),
    .vld_in(grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

maxpool_regslice_both #(
    .DataWidth( 2 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TSTRB_int_regslice),
    .vld_in(grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

maxpool_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TLAST_int_regslice),
    .vld_in(grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_start_reg <= 1'b1;
        end else if ((grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_ready == 1'b1)) begin
            grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_start_reg <= 1'b1;
        end else if ((grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_ready == 1'b1)) begin
            grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_start_reg <= 1'b1;
        end else if ((grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_ready == 1'b1)) begin
            grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TVALID == 1'b1))) begin
        out_stream_TDATA_reg <= grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TDATA;
        out_stream_TKEEP_reg <= grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TKEEP;
        out_stream_TLAST_reg <= grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TLAST;
        out_stream_TSTRB_reg <= grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TSTRB;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_stream_TREADY_int_regslice = grp_maxpool_Pipeline_READ_INPUT_fu_132_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TVALID == 1'b1))) begin
        out_stream_TDATA_int_regslice = grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TDATA;
    end else begin
        out_stream_TDATA_int_regslice = out_stream_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TVALID == 1'b1))) begin
        out_stream_TKEEP_int_regslice = grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TKEEP;
    end else begin
        out_stream_TKEEP_int_regslice = out_stream_TKEEP_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TVALID == 1'b1))) begin
        out_stream_TLAST_int_regslice = grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TLAST;
    end else begin
        out_stream_TLAST_int_regslice = out_stream_TLAST_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TVALID == 1'b1))) begin
        out_stream_TSTRB_int_regslice = grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TSTRB;
    end else begin
        out_stream_TSTRB_int_regslice = out_stream_TSTRB_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_start = grp_maxpool_Pipeline_POOL_OR_POOL_OC_fu_160_ap_start_reg;

assign grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_start = grp_maxpool_Pipeline_READ_INPUT_fu_132_ap_start_reg;

assign grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_start = grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_ap_start_reg;

assign grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state7);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign out_stream_TVALID_int_regslice = grp_maxpool_Pipeline_WRITE_OUTPUT_fu_184_out_stream_TVALID;


reg find_kernel_block = 0;
// synthesis translate_off
`include "maxpool_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //maxpool

