-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    weight_stream_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    weight_stream_TVALID : IN STD_LOGIC;
    weight_stream_TREADY : OUT STD_LOGIC;
    weight_stream_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    weight_stream_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
    weight_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    bias : IN STD_LOGIC_VECTOR (15 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (1 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of conv2d is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "conv2d_conv2d,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.004000,HLS_SYN_LAT=66,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1726,HLS_SYN_LUT=1248,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal shl_ln_fu_515_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln_reg_920 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_start : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_done : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_idle : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_ready : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_in_stream_TREADY : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_24_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_24_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_23_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_23_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_22_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_22_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_21_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_21_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_20_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_20_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_19_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_19_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_18_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_18_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_17_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_17_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_16_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_16_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_15_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_15_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_14_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_14_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_13_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_13_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_12_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_12_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_11_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_11_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_10_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_10_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_9_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_9_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_8_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_8_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_7_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_7_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_6_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_6_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_5_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_5_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_4_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_4_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_3_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_3_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_2_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_2_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_1_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_input_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_start : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_done : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_idle : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_ready : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_weight_stream_TREADY : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out1_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out2_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out3_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out4_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out5 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out5_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out6 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out6_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out7 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out7_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out8 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out8_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_start : STD_LOGIC;
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_done : STD_LOGIC;
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_idle : STD_LOGIC;
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_ready : STD_LOGIC;
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_8_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_8_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_7_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_7_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_6_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_6_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_5_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_5_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_4_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_4_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_3_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_3_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_2_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_2_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_1_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_start : STD_LOGIC;
    signal grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_done : STD_LOGIC;
    signal grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_idle : STD_LOGIC;
    signal grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_ready : STD_LOGIC;
    signal grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TREADY : STD_LOGIC;
    signal grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TVALID : STD_LOGIC;
    signal grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TKEEP : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TSTRB : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_start_reg : STD_LOGIC := '0';
    signal grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal out_stream_TDATA_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal out_stream_TKEEP_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal out_stream_TSTRB_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal out_stream_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_weight_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal weight_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal weight_stream_TVALID_int_regslice : STD_LOGIC;
    signal weight_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_weight_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_weight_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal weight_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_weight_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_weight_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_weight_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal weight_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_weight_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_weight_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_weight_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal weight_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_weight_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_weight_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal out_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_conv2d_Pipeline_READ_INPUT IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        in_stream_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        input_24_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_24_out_ap_vld : OUT STD_LOGIC;
        input_23_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_23_out_ap_vld : OUT STD_LOGIC;
        input_22_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_22_out_ap_vld : OUT STD_LOGIC;
        input_21_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_21_out_ap_vld : OUT STD_LOGIC;
        input_20_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_20_out_ap_vld : OUT STD_LOGIC;
        input_19_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_19_out_ap_vld : OUT STD_LOGIC;
        input_18_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_18_out_ap_vld : OUT STD_LOGIC;
        input_17_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_17_out_ap_vld : OUT STD_LOGIC;
        input_16_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_16_out_ap_vld : OUT STD_LOGIC;
        input_15_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_15_out_ap_vld : OUT STD_LOGIC;
        input_14_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_14_out_ap_vld : OUT STD_LOGIC;
        input_13_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_13_out_ap_vld : OUT STD_LOGIC;
        input_12_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_12_out_ap_vld : OUT STD_LOGIC;
        input_11_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_11_out_ap_vld : OUT STD_LOGIC;
        input_10_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_10_out_ap_vld : OUT STD_LOGIC;
        input_9_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_9_out_ap_vld : OUT STD_LOGIC;
        input_8_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_8_out_ap_vld : OUT STD_LOGIC;
        input_7_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_7_out_ap_vld : OUT STD_LOGIC;
        input_6_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_6_out_ap_vld : OUT STD_LOGIC;
        input_5_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_5_out_ap_vld : OUT STD_LOGIC;
        input_4_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_4_out_ap_vld : OUT STD_LOGIC;
        input_3_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_3_out_ap_vld : OUT STD_LOGIC;
        input_2_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_2_out_ap_vld : OUT STD_LOGIC;
        input_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_1_out_ap_vld : OUT STD_LOGIC;
        input_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_out_ap_vld : OUT STD_LOGIC );
    end component;


    component conv2d_conv2d_Pipeline_READ_WEIGHTS IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        weight_stream_TVALID : IN STD_LOGIC;
        weight_stream_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        weight_stream_TREADY : OUT STD_LOGIC;
        weight_stream_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
        weight_stream_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
        weight_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        p_out3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_out3_ap_vld : OUT STD_LOGIC;
        p_out4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_out4_ap_vld : OUT STD_LOGIC;
        p_out5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_out5_ap_vld : OUT STD_LOGIC;
        p_out6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_out6_ap_vld : OUT STD_LOGIC;
        p_out7 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_out7_ap_vld : OUT STD_LOGIC;
        p_out8 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_out8_ap_vld : OUT STD_LOGIC );
    end component;


    component conv2d_conv2d_Pipeline_CONV_OR_CONV_OC2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        input_1_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        input_2_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        input_5_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        input_6_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        input_7_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        input_10_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        input_11_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        input_12_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln96 : IN STD_LOGIC_VECTOR (15 downto 0);
        shl_ln : IN STD_LOGIC_VECTOR (23 downto 0);
        input_3_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        input_8_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        input_13_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln96_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_4_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        input_9_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        input_14_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln96_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_15_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        input_16_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        input_17_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln96_3 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_18_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln96_4 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_19_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln96_5 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_20_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        input_21_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        input_22_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln96_6 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_23_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln96_7 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_24_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln96_8 : IN STD_LOGIC_VECTOR (15 downto 0);
        output_8_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_8_out_ap_vld : OUT STD_LOGIC;
        output_7_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_7_out_ap_vld : OUT STD_LOGIC;
        output_6_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_6_out_ap_vld : OUT STD_LOGIC;
        output_5_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_5_out_ap_vld : OUT STD_LOGIC;
        output_4_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_4_out_ap_vld : OUT STD_LOGIC;
        output_3_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_3_out_ap_vld : OUT STD_LOGIC;
        output_2_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_2_out_ap_vld : OUT STD_LOGIC;
        output_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_1_out_ap_vld : OUT STD_LOGIC;
        output_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_out_ap_vld : OUT STD_LOGIC );
    end component;


    component conv2d_conv2d_Pipeline_WRITE_OUTPUT IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        output_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        output_1_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        output_2_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        output_3_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        output_4_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        output_5_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        output_6_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        output_7_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        output_8_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (1 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv2d_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_conv2d_Pipeline_READ_INPUT_fu_252 : component conv2d_conv2d_Pipeline_READ_INPUT
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_start,
        ap_done => grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_done,
        ap_idle => grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_idle,
        ap_ready => grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_ready,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TREADY => grp_conv2d_Pipeline_READ_INPUT_fu_252_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP_int_regslice,
        in_stream_TSTRB => in_stream_TSTRB_int_regslice,
        in_stream_TLAST => in_stream_TLAST_int_regslice,
        input_24_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_24_out,
        input_24_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_24_out_ap_vld,
        input_23_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_23_out,
        input_23_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_23_out_ap_vld,
        input_22_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_22_out,
        input_22_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_22_out_ap_vld,
        input_21_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_21_out,
        input_21_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_21_out_ap_vld,
        input_20_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_20_out,
        input_20_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_20_out_ap_vld,
        input_19_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_19_out,
        input_19_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_19_out_ap_vld,
        input_18_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_18_out,
        input_18_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_18_out_ap_vld,
        input_17_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_17_out,
        input_17_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_17_out_ap_vld,
        input_16_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_16_out,
        input_16_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_16_out_ap_vld,
        input_15_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_15_out,
        input_15_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_15_out_ap_vld,
        input_14_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_14_out,
        input_14_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_14_out_ap_vld,
        input_13_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_13_out,
        input_13_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_13_out_ap_vld,
        input_12_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_12_out,
        input_12_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_12_out_ap_vld,
        input_11_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_11_out,
        input_11_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_11_out_ap_vld,
        input_10_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_10_out,
        input_10_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_10_out_ap_vld,
        input_9_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_9_out,
        input_9_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_9_out_ap_vld,
        input_8_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_8_out,
        input_8_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_8_out_ap_vld,
        input_7_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_7_out,
        input_7_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_7_out_ap_vld,
        input_6_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_6_out,
        input_6_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_6_out_ap_vld,
        input_5_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_5_out,
        input_5_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_5_out_ap_vld,
        input_4_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_4_out,
        input_4_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_4_out_ap_vld,
        input_3_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_3_out,
        input_3_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_3_out_ap_vld,
        input_2_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_2_out,
        input_2_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_2_out_ap_vld,
        input_1_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_1_out,
        input_1_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_1_out_ap_vld,
        input_out => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_out,
        input_out_ap_vld => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_out_ap_vld);

    grp_conv2d_Pipeline_READ_WEIGHTS_fu_289 : component conv2d_conv2d_Pipeline_READ_WEIGHTS
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_start,
        ap_done => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_done,
        ap_idle => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_idle,
        ap_ready => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_ready,
        weight_stream_TVALID => weight_stream_TVALID_int_regslice,
        weight_stream_TDATA => weight_stream_TDATA_int_regslice,
        weight_stream_TREADY => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_weight_stream_TREADY,
        weight_stream_TKEEP => weight_stream_TKEEP_int_regslice,
        weight_stream_TSTRB => weight_stream_TSTRB_int_regslice,
        weight_stream_TLAST => weight_stream_TLAST_int_regslice,
        p_out => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out,
        p_out_ap_vld => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out_ap_vld,
        p_out1 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out1,
        p_out1_ap_vld => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out1_ap_vld,
        p_out2 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out2,
        p_out2_ap_vld => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out2_ap_vld,
        p_out3 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out3,
        p_out3_ap_vld => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out3_ap_vld,
        p_out4 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out4,
        p_out4_ap_vld => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out4_ap_vld,
        p_out5 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out5,
        p_out5_ap_vld => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out5_ap_vld,
        p_out6 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out6,
        p_out6_ap_vld => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out6_ap_vld,
        p_out7 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out7,
        p_out7_ap_vld => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out7_ap_vld,
        p_out8 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out8,
        p_out8_ap_vld => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out8_ap_vld);

    grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310 : component conv2d_conv2d_Pipeline_CONV_OR_CONV_OC2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_start,
        ap_done => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_done,
        ap_idle => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_idle,
        ap_ready => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_ready,
        input_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_out,
        input_1_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_1_out,
        input_2_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_2_out,
        input_5_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_5_out,
        input_6_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_6_out,
        input_7_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_7_out,
        input_10_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_10_out,
        input_11_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_11_out,
        input_12_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_12_out,
        sext_ln96 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out8,
        shl_ln => shl_ln_reg_920,
        input_3_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_3_out,
        input_8_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_8_out,
        input_13_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_13_out,
        sext_ln96_1 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out7,
        input_4_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_4_out,
        input_9_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_9_out,
        input_14_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_14_out,
        sext_ln96_2 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out6,
        input_15_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_15_out,
        input_16_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_16_out,
        input_17_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_17_out,
        sext_ln96_3 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out5,
        input_18_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_18_out,
        sext_ln96_4 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out4,
        input_19_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_19_out,
        sext_ln96_5 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out3,
        input_20_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_20_out,
        input_21_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_21_out,
        input_22_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_22_out,
        sext_ln96_6 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out2,
        input_23_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_23_out,
        sext_ln96_7 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out1,
        input_24_reload => grp_conv2d_Pipeline_READ_INPUT_fu_252_input_24_out,
        sext_ln96_8 => grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_p_out,
        output_8_out => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_8_out,
        output_8_out_ap_vld => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_8_out_ap_vld,
        output_7_out => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_7_out,
        output_7_out_ap_vld => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_7_out_ap_vld,
        output_6_out => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_6_out,
        output_6_out_ap_vld => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_6_out_ap_vld,
        output_5_out => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_5_out,
        output_5_out_ap_vld => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_5_out_ap_vld,
        output_4_out => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_4_out,
        output_4_out_ap_vld => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_4_out_ap_vld,
        output_3_out => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_3_out,
        output_3_out_ap_vld => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_3_out_ap_vld,
        output_2_out => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_2_out,
        output_2_out_ap_vld => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_2_out_ap_vld,
        output_1_out => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_1_out,
        output_1_out_ap_vld => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_1_out_ap_vld,
        output_out => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_out,
        output_out_ap_vld => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_out_ap_vld);

    grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358 : component conv2d_conv2d_Pipeline_WRITE_OUTPUT
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_start,
        ap_done => grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_done,
        ap_idle => grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_idle,
        ap_ready => grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_ready,
        out_stream_TREADY => grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TREADY,
        output_reload => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_out,
        output_1_reload => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_1_out,
        output_2_reload => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_2_out,
        output_3_reload => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_3_out,
        output_4_reload => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_4_out,
        output_5_reload => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_5_out,
        output_6_reload => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_6_out,
        output_7_reload => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_7_out,
        output_8_reload => grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_output_8_out,
        out_stream_TDATA => grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TDATA,
        out_stream_TVALID => grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TVALID,
        out_stream_TKEEP => grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TKEEP,
        out_stream_TSTRB => grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TSTRB,
        out_stream_TLAST => grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TLAST);

    regslice_both_in_stream_V_data_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_weight_stream_V_data_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => weight_stream_TDATA,
        vld_in => weight_stream_TVALID,
        ack_in => regslice_both_weight_stream_V_data_V_U_ack_in,
        data_out => weight_stream_TDATA_int_regslice,
        vld_out => weight_stream_TVALID_int_regslice,
        ack_out => weight_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_weight_stream_V_data_V_U_apdone_blk);

    regslice_both_weight_stream_V_keep_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => weight_stream_TKEEP,
        vld_in => weight_stream_TVALID,
        ack_in => regslice_both_weight_stream_V_keep_V_U_ack_in,
        data_out => weight_stream_TKEEP_int_regslice,
        vld_out => regslice_both_weight_stream_V_keep_V_U_vld_out,
        ack_out => weight_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_weight_stream_V_keep_V_U_apdone_blk);

    regslice_both_weight_stream_V_strb_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => weight_stream_TSTRB,
        vld_in => weight_stream_TVALID,
        ack_in => regslice_both_weight_stream_V_strb_V_U_ack_in,
        data_out => weight_stream_TSTRB_int_regslice,
        vld_out => regslice_both_weight_stream_V_strb_V_U_vld_out,
        ack_out => weight_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_weight_stream_V_strb_V_U_apdone_blk);

    regslice_both_weight_stream_V_last_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => weight_stream_TLAST,
        vld_in => weight_stream_TVALID,
        ack_in => regslice_both_weight_stream_V_last_V_U_ack_in,
        data_out => weight_stream_TLAST_int_regslice,
        vld_out => regslice_both_weight_stream_V_last_V_U_vld_out,
        ack_out => weight_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_weight_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDATA_int_regslice,
        vld_in => grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TVALID,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TKEEP_int_regslice,
        vld_in => grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TSTRB_int_regslice,
        vld_in => grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TLAST_int_regslice,
        vld_in => grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                out_stream_TDATA_reg <= grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TDATA;
                out_stream_TKEEP_reg <= grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TKEEP;
                out_stream_TLAST_reg <= grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TLAST;
                out_stream_TSTRB_reg <= grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TSTRB;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                    shl_ln_reg_920(23 downto 8) <= shl_ln_fu_515_p3(23 downto 8);
            end if;
        end if;
    end process;
    shl_ln_reg_920(7 downto 0) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_done, grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state8, regslice_both_out_stream_V_data_V_U_apdone_blk, ap_block_state3_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_on_subcall_done)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_done)
    begin
        if ((grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_done)
    begin
        if ((grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state8_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state3_on_subcall_done_assign_proc : process(grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_done, grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_done)
    begin
                ap_block_state3_on_subcall_done <= ((grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_done = ap_const_logic_0) or (grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state8, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_start <= grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310_ap_start_reg;
    grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_start <= grp_conv2d_Pipeline_READ_INPUT_fu_252_ap_start_reg;
    grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_start <= grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_ap_start_reg;
    grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_start <= grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_ap_start_reg;
    grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TREADY <= (out_stream_TREADY_int_regslice and ap_CS_fsm_state7);
    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(grp_conv2d_Pipeline_READ_INPUT_fu_252_in_stream_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_stream_TREADY_int_regslice <= grp_conv2d_Pipeline_READ_INPUT_fu_252_in_stream_TREADY;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    out_stream_TDATA_int_regslice_assign_proc : process(grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TDATA, grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TVALID, ap_CS_fsm_state7, out_stream_TDATA_reg)
    begin
        if (((grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            out_stream_TDATA_int_regslice <= grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TDATA;
        else 
            out_stream_TDATA_int_regslice <= out_stream_TDATA_reg;
        end if; 
    end process;


    out_stream_TKEEP_int_regslice_assign_proc : process(grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TVALID, grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TKEEP, ap_CS_fsm_state7, out_stream_TKEEP_reg)
    begin
        if (((grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            out_stream_TKEEP_int_regslice <= grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TKEEP;
        else 
            out_stream_TKEEP_int_regslice <= out_stream_TKEEP_reg;
        end if; 
    end process;


    out_stream_TLAST_int_regslice_assign_proc : process(grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TVALID, grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TLAST, ap_CS_fsm_state7, out_stream_TLAST_reg)
    begin
        if (((grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            out_stream_TLAST_int_regslice <= grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TLAST;
        else 
            out_stream_TLAST_int_regslice <= out_stream_TLAST_reg;
        end if; 
    end process;


    out_stream_TSTRB_int_regslice_assign_proc : process(grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TVALID, grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TSTRB, ap_CS_fsm_state7, out_stream_TSTRB_reg)
    begin
        if (((grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            out_stream_TSTRB_int_regslice <= grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TSTRB;
        else 
            out_stream_TSTRB_int_regslice <= out_stream_TSTRB_reg;
        end if; 
    end process;

    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;
    out_stream_TVALID_int_regslice <= grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358_out_stream_TVALID;
    shl_ln_fu_515_p3 <= (bias & ap_const_lv8_0);
    weight_stream_TREADY <= regslice_both_weight_stream_V_data_V_U_ack_in;

    weight_stream_TREADY_int_regslice_assign_proc : process(grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_weight_stream_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            weight_stream_TREADY_int_regslice <= grp_conv2d_Pipeline_READ_WEIGHTS_fu_289_weight_stream_TREADY;
        else 
            weight_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
