-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_conv2d_Pipeline_READ_INPUT is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    input_24_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_24_out_ap_vld : OUT STD_LOGIC;
    input_23_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_23_out_ap_vld : OUT STD_LOGIC;
    input_22_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_22_out_ap_vld : OUT STD_LOGIC;
    input_21_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_21_out_ap_vld : OUT STD_LOGIC;
    input_20_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_20_out_ap_vld : OUT STD_LOGIC;
    input_19_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_19_out_ap_vld : OUT STD_LOGIC;
    input_18_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_18_out_ap_vld : OUT STD_LOGIC;
    input_17_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_17_out_ap_vld : OUT STD_LOGIC;
    input_16_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_16_out_ap_vld : OUT STD_LOGIC;
    input_15_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_15_out_ap_vld : OUT STD_LOGIC;
    input_14_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_14_out_ap_vld : OUT STD_LOGIC;
    input_13_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_13_out_ap_vld : OUT STD_LOGIC;
    input_12_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_12_out_ap_vld : OUT STD_LOGIC;
    input_11_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_11_out_ap_vld : OUT STD_LOGIC;
    input_10_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_10_out_ap_vld : OUT STD_LOGIC;
    input_9_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_9_out_ap_vld : OUT STD_LOGIC;
    input_8_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_8_out_ap_vld : OUT STD_LOGIC;
    input_7_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_7_out_ap_vld : OUT STD_LOGIC;
    input_6_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_6_out_ap_vld : OUT STD_LOGIC;
    input_5_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_5_out_ap_vld : OUT STD_LOGIC;
    input_4_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_4_out_ap_vld : OUT STD_LOGIC;
    input_3_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_3_out_ap_vld : OUT STD_LOGIC;
    input_2_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_2_out_ap_vld : OUT STD_LOGIC;
    input_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_1_out_ap_vld : OUT STD_LOGIC;
    input_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of conv2d_conv2d_Pipeline_READ_INPUT is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv11_34 : STD_LOGIC_VECTOR (10 downto 0) := "00000110100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln57_fu_449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal trunc_ln1_reg_935 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln68_fu_480_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln68_reg_939 : STD_LOGIC_VECTOR (2 downto 0);
    signal phi_urem_fu_118 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal select_ln47_fu_509_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_phi_urem_load : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal phi_mul_fu_122 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln66_fu_464_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_phi_mul_load : STD_LOGIC_VECTOR (10 downto 0);
    signal rem_fu_126 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal i_fu_455_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_i_3 : STD_LOGIC_VECTOR (4 downto 0);
    signal input_fu_130 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal input_1_fu_134 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_2_fu_138 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_3_fu_142 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_4_fu_146 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_5_fu_150 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_6_fu_154 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_7_fu_158 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_8_fu_162 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_9_fu_166 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_10_fu_170 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_11_fu_174 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_12_fu_178 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_13_fu_182 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_14_fu_186 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_15_fu_190 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_16_fu_194 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_17_fu_198 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_18_fu_202 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_19_fu_206 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_20_fu_210 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_21_fu_214 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_22_fu_218 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_23_fu_222 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input_24_fu_226 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal icmp_ln47_fu_503_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln47_fu_497_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component conv2d_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    phi_mul_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln57_fu_449_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    phi_mul_fu_122 <= add_ln66_fu_464_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    phi_mul_fu_122 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    phi_urem_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln57_fu_449_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    phi_urem_fu_118 <= select_ln47_fu_509_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    phi_urem_fu_118 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    rem_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln57_fu_449_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    rem_fu_126 <= i_fu_455_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    rem_fu_126 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_0) and (trunc_ln1_reg_935 = ap_const_lv3_2))) then
                input_10_fu_170 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_1) and (trunc_ln1_reg_935 = ap_const_lv3_2))) then
                input_11_fu_174 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_2) and (trunc_ln1_reg_935 = ap_const_lv3_2))) then
                input_12_fu_178 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_3) and (trunc_ln1_reg_935 = ap_const_lv3_2))) then
                input_13_fu_182 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((trunc_ln68_reg_939 = ap_const_lv3_3)) and not((trunc_ln68_reg_939 = ap_const_lv3_2)) and not((trunc_ln68_reg_939 = ap_const_lv3_1)) and not((trunc_ln68_reg_939 = ap_const_lv3_0)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln1_reg_935 = ap_const_lv3_2))) then
                input_14_fu_186 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_0) and (trunc_ln1_reg_935 = ap_const_lv3_3))) then
                input_15_fu_190 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_1) and (trunc_ln1_reg_935 = ap_const_lv3_3))) then
                input_16_fu_194 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_2) and (trunc_ln1_reg_935 = ap_const_lv3_3))) then
                input_17_fu_198 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_3) and (trunc_ln1_reg_935 = ap_const_lv3_3))) then
                input_18_fu_202 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((trunc_ln68_reg_939 = ap_const_lv3_3)) and not((trunc_ln68_reg_939 = ap_const_lv3_2)) and not((trunc_ln68_reg_939 = ap_const_lv3_1)) and not((trunc_ln68_reg_939 = ap_const_lv3_0)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln1_reg_935 = ap_const_lv3_3))) then
                input_19_fu_206 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_1) and (trunc_ln1_reg_935 = ap_const_lv3_0))) then
                input_1_fu_134 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((trunc_ln1_reg_935 = ap_const_lv3_3)) and not((trunc_ln1_reg_935 = ap_const_lv3_2)) and not((trunc_ln1_reg_935 = ap_const_lv3_1)) and not((trunc_ln1_reg_935 = ap_const_lv3_0)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_0))) then
                input_20_fu_210 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((trunc_ln1_reg_935 = ap_const_lv3_3)) and not((trunc_ln1_reg_935 = ap_const_lv3_2)) and not((trunc_ln1_reg_935 = ap_const_lv3_1)) and not((trunc_ln1_reg_935 = ap_const_lv3_0)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_1))) then
                input_21_fu_214 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((trunc_ln1_reg_935 = ap_const_lv3_3)) and not((trunc_ln1_reg_935 = ap_const_lv3_2)) and not((trunc_ln1_reg_935 = ap_const_lv3_1)) and not((trunc_ln1_reg_935 = ap_const_lv3_0)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_2))) then
                input_22_fu_218 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((trunc_ln1_reg_935 = ap_const_lv3_3)) and not((trunc_ln1_reg_935 = ap_const_lv3_2)) and not((trunc_ln1_reg_935 = ap_const_lv3_1)) and not((trunc_ln1_reg_935 = ap_const_lv3_0)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_3))) then
                input_23_fu_222 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((trunc_ln1_reg_935 = ap_const_lv3_3)) and not((trunc_ln1_reg_935 = ap_const_lv3_2)) and not((trunc_ln1_reg_935 = ap_const_lv3_1)) and not((trunc_ln68_reg_939 = ap_const_lv3_3)) and not((trunc_ln68_reg_939 = ap_const_lv3_2)) and not((trunc_ln68_reg_939 = ap_const_lv3_1)) and not((trunc_ln68_reg_939 = ap_const_lv3_0)) and not((trunc_ln1_reg_935 = ap_const_lv3_0)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                input_24_fu_226 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_2) and (trunc_ln1_reg_935 = ap_const_lv3_0))) then
                input_2_fu_138 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_3) and (trunc_ln1_reg_935 = ap_const_lv3_0))) then
                input_3_fu_142 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((trunc_ln68_reg_939 = ap_const_lv3_3)) and not((trunc_ln68_reg_939 = ap_const_lv3_2)) and not((trunc_ln68_reg_939 = ap_const_lv3_1)) and not((trunc_ln68_reg_939 = ap_const_lv3_0)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln1_reg_935 = ap_const_lv3_0))) then
                input_4_fu_146 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_0) and (trunc_ln1_reg_935 = ap_const_lv3_1))) then
                input_5_fu_150 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_1) and (trunc_ln1_reg_935 = ap_const_lv3_1))) then
                input_6_fu_154 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_2) and (trunc_ln1_reg_935 = ap_const_lv3_1))) then
                input_7_fu_158 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_3) and (trunc_ln1_reg_935 = ap_const_lv3_1))) then
                input_8_fu_162 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((trunc_ln68_reg_939 = ap_const_lv3_3)) and not((trunc_ln68_reg_939 = ap_const_lv3_2)) and not((trunc_ln68_reg_939 = ap_const_lv3_1)) and not((trunc_ln68_reg_939 = ap_const_lv3_0)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln1_reg_935 = ap_const_lv3_1))) then
                input_9_fu_166 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln68_reg_939 = ap_const_lv3_0) and (trunc_ln1_reg_935 = ap_const_lv3_0))) then
                input_fu_130 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln1_reg_935 <= ap_sig_allocacmp_phi_mul_load(10 downto 8);
                trunc_ln68_reg_939 <= trunc_ln68_fu_480_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln47_fu_497_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_urem_load) + unsigned(ap_const_lv5_1));
    add_ln66_fu_464_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_mul_load) + unsigned(ap_const_lv11_34));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, in_stream_TVALID)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((in_stream_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, in_stream_TVALID)
    begin
                ap_block_pp0_stage0_11001 <= ((in_stream_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, in_stream_TVALID)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((in_stream_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, in_stream_TVALID)
    begin
                ap_block_pp0_stage0_subdone <= ((in_stream_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln57_fu_449_p2)
    begin
        if (((icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, rem_fu_126)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_3 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_3 <= rem_fu_126;
        end if; 
    end process;


    ap_sig_allocacmp_phi_mul_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, phi_mul_fu_122)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_phi_mul_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_phi_mul_load <= phi_mul_fu_122;
        end if; 
    end process;


    ap_sig_allocacmp_phi_urem_load_assign_proc : process(ap_CS_fsm_pp0_stage0, phi_urem_fu_118, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_phi_urem_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_phi_urem_load <= phi_urem_fu_118;
        end if; 
    end process;

    i_fu_455_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_3) + unsigned(ap_const_lv5_1));
    icmp_ln47_fu_503_p2 <= "1" when (ap_sig_allocacmp_phi_urem_load = ap_const_lv5_4) else "0";
    icmp_ln57_fu_449_p2 <= "1" when (ap_sig_allocacmp_i_3 = ap_const_lv5_19) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, in_stream_TVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    input_10_out <= input_10_fu_170;

    input_10_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_10_out_ap_vld <= ap_const_logic_1;
        else 
            input_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_11_out <= input_11_fu_174;

    input_11_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_11_out_ap_vld <= ap_const_logic_1;
        else 
            input_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_12_out <= input_12_fu_178;

    input_12_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_12_out_ap_vld <= ap_const_logic_1;
        else 
            input_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_13_out <= input_13_fu_182;

    input_13_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_13_out_ap_vld <= ap_const_logic_1;
        else 
            input_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_14_out <= input_14_fu_186;

    input_14_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_14_out_ap_vld <= ap_const_logic_1;
        else 
            input_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_15_out <= input_15_fu_190;

    input_15_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_15_out_ap_vld <= ap_const_logic_1;
        else 
            input_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_16_out <= input_16_fu_194;

    input_16_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_16_out_ap_vld <= ap_const_logic_1;
        else 
            input_16_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_17_out <= input_17_fu_198;

    input_17_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_17_out_ap_vld <= ap_const_logic_1;
        else 
            input_17_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_18_out <= input_18_fu_202;

    input_18_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_18_out_ap_vld <= ap_const_logic_1;
        else 
            input_18_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_19_out <= input_19_fu_206;

    input_19_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_19_out_ap_vld <= ap_const_logic_1;
        else 
            input_19_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_1_out <= input_1_fu_134;

    input_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_1_out_ap_vld <= ap_const_logic_1;
        else 
            input_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_20_out <= input_20_fu_210;

    input_20_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_20_out_ap_vld <= ap_const_logic_1;
        else 
            input_20_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_21_out <= input_21_fu_214;

    input_21_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_21_out_ap_vld <= ap_const_logic_1;
        else 
            input_21_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_22_out <= input_22_fu_218;

    input_22_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_22_out_ap_vld <= ap_const_logic_1;
        else 
            input_22_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_23_out <= input_23_fu_222;

    input_23_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_23_out_ap_vld <= ap_const_logic_1;
        else 
            input_23_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_24_out <= input_24_fu_226;

    input_24_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_24_out_ap_vld <= ap_const_logic_1;
        else 
            input_24_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_2_out <= input_2_fu_138;

    input_2_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_2_out_ap_vld <= ap_const_logic_1;
        else 
            input_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_3_out <= input_3_fu_142;

    input_3_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_3_out_ap_vld <= ap_const_logic_1;
        else 
            input_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_4_out <= input_4_fu_146;

    input_4_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_4_out_ap_vld <= ap_const_logic_1;
        else 
            input_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_5_out <= input_5_fu_150;

    input_5_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_5_out_ap_vld <= ap_const_logic_1;
        else 
            input_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_6_out <= input_6_fu_154;

    input_6_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_6_out_ap_vld <= ap_const_logic_1;
        else 
            input_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_7_out <= input_7_fu_158;

    input_7_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_7_out_ap_vld <= ap_const_logic_1;
        else 
            input_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_8_out <= input_8_fu_162;

    input_8_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_8_out_ap_vld <= ap_const_logic_1;
        else 
            input_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_9_out <= input_9_fu_166;

    input_9_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_9_out_ap_vld <= ap_const_logic_1;
        else 
            input_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    input_out <= input_fu_130;

    input_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_fu_449_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln57_fu_449_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_out_ap_vld <= ap_const_logic_1;
        else 
            input_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln47_fu_509_p3 <= 
        ap_const_lv5_0 when (icmp_ln47_fu_503_p2(0) = '1') else 
        add_ln47_fu_497_p2;
    trunc_ln68_fu_480_p1 <= ap_sig_allocacmp_phi_urem_load(3 - 1 downto 0);
end behav;
