# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/kv260_constraints.xdc

# Block Designs: bd/cnn_pipeline/cnn_pipeline.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_pipeline || ORIG_REF_NAME==cnn_pipeline} -quiet] -quiet

# IP: bd/cnn_pipeline/ip/cnn_pipeline_zynq_ultra_ps_e_0_1/cnn_pipeline_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_pipeline_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==cnn_pipeline_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/cnn_pipeline/ip/cnn_pipeline_proc_sys_reset_0_1/cnn_pipeline_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_pipeline_proc_sys_reset_0_1 || ORIG_REF_NAME==cnn_pipeline_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/cnn_pipeline/ip/cnn_pipeline_axi_dma_0_1/cnn_pipeline_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_pipeline_axi_dma_0_1 || ORIG_REF_NAME==cnn_pipeline_axi_dma_0_1} -quiet] -quiet

# IP: bd/cnn_pipeline/ip/cnn_pipeline_conv2d_0_1/cnn_pipeline_conv2d_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_pipeline_conv2d_0_1 || ORIG_REF_NAME==cnn_pipeline_conv2d_0_1} -quiet] -quiet

# IP: bd/cnn_pipeline/ip/cnn_pipeline_relu_0_1/cnn_pipeline_relu_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_pipeline_relu_0_1 || ORIG_REF_NAME==cnn_pipeline_relu_0_1} -quiet] -quiet

# IP: bd/cnn_pipeline/ip/cnn_pipeline_maxpool_0_1/cnn_pipeline_maxpool_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_pipeline_maxpool_0_1 || ORIG_REF_NAME==cnn_pipeline_maxpool_0_1} -quiet] -quiet

# IP: bd/cnn_pipeline/ip/cnn_pipeline_axi_smc_0/cnn_pipeline_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_pipeline_axi_smc_0 || ORIG_REF_NAME==cnn_pipeline_axi_smc_0} -quiet] -quiet

# IP: bd/cnn_pipeline/ip/cnn_pipeline_axi_smc_1_0/cnn_pipeline_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_pipeline_axi_smc_1_0 || ORIG_REF_NAME==cnn_pipeline_axi_smc_1_0} -quiet] -quiet

# IP: bd/cnn_pipeline/ip/cnn_pipeline_fifo_generator_0_0/cnn_pipeline_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_pipeline_fifo_generator_0_0 || ORIG_REF_NAME==cnn_pipeline_fifo_generator_0_0} -quiet] -quiet

# IP: bd/cnn_pipeline/ip/cnn_pipeline_xlconstant_0_0/cnn_pipeline_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_pipeline_xlconstant_0_0 || ORIG_REF_NAME==cnn_pipeline_xlconstant_0_0} -quiet] -quiet

# IP: bd/cnn_pipeline/ip/cnn_pipeline_xlconstant_1_0/cnn_pipeline_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_pipeline_xlconstant_1_0 || ORIG_REF_NAME==cnn_pipeline_xlconstant_1_0} -quiet] -quiet

# XDC: c:/CHINNA/Vivado_workspace/cnn_accelerator/cnn_accelerator.gen/sources_1/bd/cnn_pipeline/cnn_pipeline_ooc.xdc
