// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module conv2d_conv2d_Pipeline_READ_INPUT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        input_24_out,
        input_24_out_ap_vld,
        input_23_out,
        input_23_out_ap_vld,
        input_22_out,
        input_22_out_ap_vld,
        input_21_out,
        input_21_out_ap_vld,
        input_20_out,
        input_20_out_ap_vld,
        input_19_out,
        input_19_out_ap_vld,
        input_18_out,
        input_18_out_ap_vld,
        input_17_out,
        input_17_out_ap_vld,
        input_16_out,
        input_16_out_ap_vld,
        input_15_out,
        input_15_out_ap_vld,
        input_14_out,
        input_14_out_ap_vld,
        input_13_out,
        input_13_out_ap_vld,
        input_12_out,
        input_12_out_ap_vld,
        input_11_out,
        input_11_out_ap_vld,
        input_10_out,
        input_10_out_ap_vld,
        input_9_out,
        input_9_out_ap_vld,
        input_8_out,
        input_8_out_ap_vld,
        input_7_out,
        input_7_out_ap_vld,
        input_6_out,
        input_6_out_ap_vld,
        input_5_out,
        input_5_out_ap_vld,
        input_4_out,
        input_4_out_ap_vld,
        input_3_out,
        input_3_out_ap_vld,
        input_2_out,
        input_2_out_ap_vld,
        input_1_out,
        input_1_out_ap_vld,
        input_out,
        input_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input  [15:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [1:0] in_stream_TKEEP;
input  [1:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [15:0] input_24_out;
output   input_24_out_ap_vld;
output  [15:0] input_23_out;
output   input_23_out_ap_vld;
output  [15:0] input_22_out;
output   input_22_out_ap_vld;
output  [15:0] input_21_out;
output   input_21_out_ap_vld;
output  [15:0] input_20_out;
output   input_20_out_ap_vld;
output  [15:0] input_19_out;
output   input_19_out_ap_vld;
output  [15:0] input_18_out;
output   input_18_out_ap_vld;
output  [15:0] input_17_out;
output   input_17_out_ap_vld;
output  [15:0] input_16_out;
output   input_16_out_ap_vld;
output  [15:0] input_15_out;
output   input_15_out_ap_vld;
output  [15:0] input_14_out;
output   input_14_out_ap_vld;
output  [15:0] input_13_out;
output   input_13_out_ap_vld;
output  [15:0] input_12_out;
output   input_12_out_ap_vld;
output  [15:0] input_11_out;
output   input_11_out_ap_vld;
output  [15:0] input_10_out;
output   input_10_out_ap_vld;
output  [15:0] input_9_out;
output   input_9_out_ap_vld;
output  [15:0] input_8_out;
output   input_8_out_ap_vld;
output  [15:0] input_7_out;
output   input_7_out_ap_vld;
output  [15:0] input_6_out;
output   input_6_out_ap_vld;
output  [15:0] input_5_out;
output   input_5_out_ap_vld;
output  [15:0] input_4_out;
output   input_4_out_ap_vld;
output  [15:0] input_3_out;
output   input_3_out_ap_vld;
output  [15:0] input_2_out;
output   input_2_out_ap_vld;
output  [15:0] input_1_out;
output   input_1_out_ap_vld;
output  [15:0] input_out;
output   input_out_ap_vld;

reg ap_idle;
reg in_stream_TREADY;
reg input_24_out_ap_vld;
reg input_23_out_ap_vld;
reg input_22_out_ap_vld;
reg input_21_out_ap_vld;
reg input_20_out_ap_vld;
reg input_19_out_ap_vld;
reg input_18_out_ap_vld;
reg input_17_out_ap_vld;
reg input_16_out_ap_vld;
reg input_15_out_ap_vld;
reg input_14_out_ap_vld;
reg input_13_out_ap_vld;
reg input_12_out_ap_vld;
reg input_11_out_ap_vld;
reg input_10_out_ap_vld;
reg input_9_out_ap_vld;
reg input_8_out_ap_vld;
reg input_7_out_ap_vld;
reg input_6_out_ap_vld;
reg input_5_out_ap_vld;
reg input_4_out_ap_vld;
reg input_3_out_ap_vld;
reg input_2_out_ap_vld;
reg input_1_out_ap_vld;
reg input_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln57_fu_449_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg   [2:0] trunc_ln1_reg_935;
reg    ap_block_pp0_stage0_11001;
wire   [2:0] trunc_ln68_fu_480_p1;
reg   [2:0] trunc_ln68_reg_939;
reg   [4:0] phi_urem_fu_118;
wire   [4:0] select_ln47_fu_509_p3;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_phi_urem_load;
wire    ap_block_pp0_stage0;
reg   [10:0] phi_mul_fu_122;
wire   [10:0] add_ln66_fu_464_p2;
reg   [10:0] ap_sig_allocacmp_phi_mul_load;
reg   [4:0] rem_fu_126;
wire   [4:0] i_fu_455_p2;
reg   [4:0] ap_sig_allocacmp_i_3;
reg   [15:0] input_fu_130;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [15:0] input_1_fu_134;
reg   [15:0] input_2_fu_138;
reg   [15:0] input_3_fu_142;
reg   [15:0] input_4_fu_146;
reg   [15:0] input_5_fu_150;
reg   [15:0] input_6_fu_154;
reg   [15:0] input_7_fu_158;
reg   [15:0] input_8_fu_162;
reg   [15:0] input_9_fu_166;
reg   [15:0] input_10_fu_170;
reg   [15:0] input_11_fu_174;
reg   [15:0] input_12_fu_178;
reg   [15:0] input_13_fu_182;
reg   [15:0] input_14_fu_186;
reg   [15:0] input_15_fu_190;
reg   [15:0] input_16_fu_194;
reg   [15:0] input_17_fu_198;
reg   [15:0] input_18_fu_202;
reg   [15:0] input_19_fu_206;
reg   [15:0] input_20_fu_210;
reg   [15:0] input_21_fu_214;
reg   [15:0] input_22_fu_218;
reg   [15:0] input_23_fu_222;
reg   [15:0] input_24_fu_226;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [0:0] icmp_ln47_fu_503_p2;
wire   [4:0] add_ln47_fu_497_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 phi_urem_fu_118 = 5'd0;
#0 phi_mul_fu_122 = 11'd0;
#0 rem_fu_126 = 5'd0;
#0 input_fu_130 = 16'd0;
#0 input_1_fu_134 = 16'd0;
#0 input_2_fu_138 = 16'd0;
#0 input_3_fu_142 = 16'd0;
#0 input_4_fu_146 = 16'd0;
#0 input_5_fu_150 = 16'd0;
#0 input_6_fu_154 = 16'd0;
#0 input_7_fu_158 = 16'd0;
#0 input_8_fu_162 = 16'd0;
#0 input_9_fu_166 = 16'd0;
#0 input_10_fu_170 = 16'd0;
#0 input_11_fu_174 = 16'd0;
#0 input_12_fu_178 = 16'd0;
#0 input_13_fu_182 = 16'd0;
#0 input_14_fu_186 = 16'd0;
#0 input_15_fu_190 = 16'd0;
#0 input_16_fu_194 = 16'd0;
#0 input_17_fu_198 = 16'd0;
#0 input_18_fu_202 = 16'd0;
#0 input_19_fu_206 = 16'd0;
#0 input_20_fu_210 = 16'd0;
#0 input_21_fu_214 = 16'd0;
#0 input_22_fu_218 = 16'd0;
#0 input_23_fu_222 = 16'd0;
#0 input_24_fu_226 = 16'd0;
#0 ap_done_reg = 1'b0;
end

conv2d_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln57_fu_449_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            phi_mul_fu_122 <= add_ln66_fu_464_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_mul_fu_122 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln57_fu_449_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            phi_urem_fu_118 <= select_ln47_fu_509_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_urem_fu_118 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln57_fu_449_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            rem_fu_126 <= i_fu_455_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            rem_fu_126 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd0) & (trunc_ln1_reg_935 == 3'd2))) begin
        input_10_fu_170 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd1) & (trunc_ln1_reg_935 == 3'd2))) begin
        input_11_fu_174 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd2) & (trunc_ln1_reg_935 == 3'd2))) begin
        input_12_fu_178 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd3) & (trunc_ln1_reg_935 == 3'd2))) begin
        input_13_fu_182 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln68_reg_939 == 3'd3) & ~(trunc_ln68_reg_939 == 3'd2) & ~(trunc_ln68_reg_939 == 3'd1) & ~(trunc_ln68_reg_939 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln1_reg_935 == 3'd2))) begin
        input_14_fu_186 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd0) & (trunc_ln1_reg_935 == 3'd3))) begin
        input_15_fu_190 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd1) & (trunc_ln1_reg_935 == 3'd3))) begin
        input_16_fu_194 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd2) & (trunc_ln1_reg_935 == 3'd3))) begin
        input_17_fu_198 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd3) & (trunc_ln1_reg_935 == 3'd3))) begin
        input_18_fu_202 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln68_reg_939 == 3'd3) & ~(trunc_ln68_reg_939 == 3'd2) & ~(trunc_ln68_reg_939 == 3'd1) & ~(trunc_ln68_reg_939 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln1_reg_935 == 3'd3))) begin
        input_19_fu_206 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd1) & (trunc_ln1_reg_935 == 3'd0))) begin
        input_1_fu_134 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln1_reg_935 == 3'd3) & ~(trunc_ln1_reg_935 == 3'd2) & ~(trunc_ln1_reg_935 == 3'd1) & ~(trunc_ln1_reg_935 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd0))) begin
        input_20_fu_210 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln1_reg_935 == 3'd3) & ~(trunc_ln1_reg_935 == 3'd2) & ~(trunc_ln1_reg_935 == 3'd1) & ~(trunc_ln1_reg_935 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd1))) begin
        input_21_fu_214 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln1_reg_935 == 3'd3) & ~(trunc_ln1_reg_935 == 3'd2) & ~(trunc_ln1_reg_935 == 3'd1) & ~(trunc_ln1_reg_935 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd2))) begin
        input_22_fu_218 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln1_reg_935 == 3'd3) & ~(trunc_ln1_reg_935 == 3'd2) & ~(trunc_ln1_reg_935 == 3'd1) & ~(trunc_ln1_reg_935 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd3))) begin
        input_23_fu_222 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln1_reg_935 == 3'd3) & ~(trunc_ln1_reg_935 == 3'd2) & ~(trunc_ln1_reg_935 == 3'd1) & ~(trunc_ln68_reg_939 == 3'd3) & ~(trunc_ln68_reg_939 == 3'd2) & ~(trunc_ln68_reg_939 == 3'd1) & ~(trunc_ln68_reg_939 == 3'd0) & ~(trunc_ln1_reg_935 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_24_fu_226 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd2) & (trunc_ln1_reg_935 == 3'd0))) begin
        input_2_fu_138 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd3) & (trunc_ln1_reg_935 == 3'd0))) begin
        input_3_fu_142 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln68_reg_939 == 3'd3) & ~(trunc_ln68_reg_939 == 3'd2) & ~(trunc_ln68_reg_939 == 3'd1) & ~(trunc_ln68_reg_939 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln1_reg_935 == 3'd0))) begin
        input_4_fu_146 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd0) & (trunc_ln1_reg_935 == 3'd1))) begin
        input_5_fu_150 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd1) & (trunc_ln1_reg_935 == 3'd1))) begin
        input_6_fu_154 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd2) & (trunc_ln1_reg_935 == 3'd1))) begin
        input_7_fu_158 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd3) & (trunc_ln1_reg_935 == 3'd1))) begin
        input_8_fu_162 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln68_reg_939 == 3'd3) & ~(trunc_ln68_reg_939 == 3'd2) & ~(trunc_ln68_reg_939 == 3'd1) & ~(trunc_ln68_reg_939 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln1_reg_935 == 3'd1))) begin
        input_9_fu_166 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln68_reg_939 == 3'd0) & (trunc_ln1_reg_935 == 3'd0))) begin
        input_fu_130 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln1_reg_935 <= {{ap_sig_allocacmp_phi_mul_load[10:8]}};
        trunc_ln68_reg_939 <= trunc_ln68_fu_480_p1;
    end
end

always @ (*) begin
    if (((icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_3 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_3 = rem_fu_126;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_phi_mul_load = 11'd0;
    end else begin
        ap_sig_allocacmp_phi_mul_load = phi_mul_fu_122;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_phi_urem_load = 5'd0;
    end else begin
        ap_sig_allocacmp_phi_urem_load = phi_urem_fu_118;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_10_out_ap_vld = 1'b1;
    end else begin
        input_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_11_out_ap_vld = 1'b1;
    end else begin
        input_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_12_out_ap_vld = 1'b1;
    end else begin
        input_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_13_out_ap_vld = 1'b1;
    end else begin
        input_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_14_out_ap_vld = 1'b1;
    end else begin
        input_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_15_out_ap_vld = 1'b1;
    end else begin
        input_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_16_out_ap_vld = 1'b1;
    end else begin
        input_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_17_out_ap_vld = 1'b1;
    end else begin
        input_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_18_out_ap_vld = 1'b1;
    end else begin
        input_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_19_out_ap_vld = 1'b1;
    end else begin
        input_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_1_out_ap_vld = 1'b1;
    end else begin
        input_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_20_out_ap_vld = 1'b1;
    end else begin
        input_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_21_out_ap_vld = 1'b1;
    end else begin
        input_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_22_out_ap_vld = 1'b1;
    end else begin
        input_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_23_out_ap_vld = 1'b1;
    end else begin
        input_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_24_out_ap_vld = 1'b1;
    end else begin
        input_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_2_out_ap_vld = 1'b1;
    end else begin
        input_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_3_out_ap_vld = 1'b1;
    end else begin
        input_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_4_out_ap_vld = 1'b1;
    end else begin
        input_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_5_out_ap_vld = 1'b1;
    end else begin
        input_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_6_out_ap_vld = 1'b1;
    end else begin
        input_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_7_out_ap_vld = 1'b1;
    end else begin
        input_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_8_out_ap_vld = 1'b1;
    end else begin
        input_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_9_out_ap_vld = 1'b1;
    end else begin
        input_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln57_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_out_ap_vld = 1'b1;
    end else begin
        input_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln47_fu_497_p2 = (ap_sig_allocacmp_phi_urem_load + 5'd1);

assign add_ln66_fu_464_p2 = (ap_sig_allocacmp_phi_mul_load + 11'd52);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((in_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((in_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((in_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((in_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign i_fu_455_p2 = (ap_sig_allocacmp_i_3 + 5'd1);

assign icmp_ln47_fu_503_p2 = ((ap_sig_allocacmp_phi_urem_load == 5'd4) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_449_p2 = ((ap_sig_allocacmp_i_3 == 5'd25) ? 1'b1 : 1'b0);

assign input_10_out = input_10_fu_170;

assign input_11_out = input_11_fu_174;

assign input_12_out = input_12_fu_178;

assign input_13_out = input_13_fu_182;

assign input_14_out = input_14_fu_186;

assign input_15_out = input_15_fu_190;

assign input_16_out = input_16_fu_194;

assign input_17_out = input_17_fu_198;

assign input_18_out = input_18_fu_202;

assign input_19_out = input_19_fu_206;

assign input_1_out = input_1_fu_134;

assign input_20_out = input_20_fu_210;

assign input_21_out = input_21_fu_214;

assign input_22_out = input_22_fu_218;

assign input_23_out = input_23_fu_222;

assign input_24_out = input_24_fu_226;

assign input_2_out = input_2_fu_138;

assign input_3_out = input_3_fu_142;

assign input_4_out = input_4_fu_146;

assign input_5_out = input_5_fu_150;

assign input_6_out = input_6_fu_154;

assign input_7_out = input_7_fu_158;

assign input_8_out = input_8_fu_162;

assign input_9_out = input_9_fu_166;

assign input_out = input_fu_130;

assign select_ln47_fu_509_p3 = ((icmp_ln47_fu_503_p2[0:0] == 1'b1) ? 5'd0 : add_ln47_fu_497_p2);

assign trunc_ln68_fu_480_p1 = ap_sig_allocacmp_phi_urem_load[2:0];

endmodule //conv2d_conv2d_Pipeline_READ_INPUT
