// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module conv2d_conv2d_Pipeline_READ_WEIGHTS (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        weight_stream_TVALID,
        weight_stream_TDATA,
        weight_stream_TREADY,
        weight_stream_TKEEP,
        weight_stream_TSTRB,
        weight_stream_TLAST,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld,
        p_out2,
        p_out2_ap_vld,
        p_out3,
        p_out3_ap_vld,
        p_out4,
        p_out4_ap_vld,
        p_out5,
        p_out5_ap_vld,
        p_out6,
        p_out6_ap_vld,
        p_out7,
        p_out7_ap_vld,
        p_out8,
        p_out8_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   weight_stream_TVALID;
input  [15:0] weight_stream_TDATA;
output   weight_stream_TREADY;
input  [1:0] weight_stream_TKEEP;
input  [1:0] weight_stream_TSTRB;
input  [0:0] weight_stream_TLAST;
output  [15:0] p_out;
output   p_out_ap_vld;
output  [15:0] p_out1;
output   p_out1_ap_vld;
output  [15:0] p_out2;
output   p_out2_ap_vld;
output  [15:0] p_out3;
output   p_out3_ap_vld;
output  [15:0] p_out4;
output   p_out4_ap_vld;
output  [15:0] p_out5;
output   p_out5_ap_vld;
output  [15:0] p_out6;
output   p_out6_ap_vld;
output  [15:0] p_out7;
output   p_out7_ap_vld;
output  [15:0] p_out8;
output   p_out8_ap_vld;

reg ap_idle;
reg weight_stream_TREADY;
reg p_out_ap_vld;
reg p_out1_ap_vld;
reg p_out2_ap_vld;
reg p_out3_ap_vld;
reg p_out4_ap_vld;
reg p_out5_ap_vld;
reg p_out6_ap_vld;
reg p_out7_ap_vld;
reg p_out8_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln73_fu_233_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    weight_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg   [1:0] trunc_ln4_reg_475;
reg    ap_block_pp0_stage0_11001;
wire   [1:0] trunc_ln83_fu_264_p1;
reg   [1:0] trunc_ln83_reg_479;
reg   [3:0] phi_urem16_fu_82;
wire   [3:0] select_ln73_fu_289_p3;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_phi_urem16_load;
wire    ap_block_pp0_stage0;
reg   [7:0] phi_mul14_fu_86;
wire   [7:0] add_ln81_fu_248_p2;
reg   [7:0] ap_sig_allocacmp_phi_mul14_load;
reg   [3:0] rem_fu_90;
wire   [3:0] i_fu_239_p2;
reg   [3:0] ap_sig_allocacmp_i_2;
reg   [15:0] empty_fu_94;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [15:0] empty_19_fu_98;
reg   [15:0] empty_20_fu_102;
reg   [15:0] empty_21_fu_106;
reg   [15:0] empty_22_fu_110;
reg   [15:0] empty_23_fu_114;
reg   [15:0] empty_24_fu_118;
reg   [15:0] empty_25_fu_122;
reg   [15:0] empty_26_fu_126;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [0:0] icmp_ln73_1_fu_283_p2;
wire   [3:0] add_ln73_1_fu_277_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 phi_urem16_fu_82 = 4'd0;
#0 phi_mul14_fu_86 = 8'd0;
#0 rem_fu_90 = 4'd0;
#0 empty_fu_94 = 16'd0;
#0 empty_19_fu_98 = 16'd0;
#0 empty_20_fu_102 = 16'd0;
#0 empty_21_fu_106 = 16'd0;
#0 empty_22_fu_110 = 16'd0;
#0 empty_23_fu_114 = 16'd0;
#0 empty_24_fu_118 = 16'd0;
#0 empty_25_fu_122 = 16'd0;
#0 empty_26_fu_126 = 16'd0;
#0 ap_done_reg = 1'b0;
end

conv2d_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln73_fu_233_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            phi_mul14_fu_86 <= add_ln81_fu_248_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_mul14_fu_86 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln73_fu_233_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            phi_urem16_fu_82 <= select_ln73_fu_289_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_urem16_fu_82 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln73_fu_233_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            rem_fu_90 <= i_fu_239_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            rem_fu_90 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln83_reg_479 == 2'd1) & (trunc_ln4_reg_475 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_19_fu_98 <= weight_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln83_reg_479 == 2'd1) & ~(trunc_ln83_reg_479 == 2'd0) & (trunc_ln4_reg_475 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_20_fu_102 <= weight_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln83_reg_479 == 2'd0) & (trunc_ln4_reg_475 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_21_fu_106 <= weight_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln83_reg_479 == 2'd1) & (trunc_ln4_reg_475 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_22_fu_110 <= weight_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln83_reg_479 == 2'd1) & ~(trunc_ln83_reg_479 == 2'd0) & (trunc_ln4_reg_475 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_23_fu_114 <= weight_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln4_reg_475 == 2'd1) & ~(trunc_ln4_reg_475 == 2'd0) & (trunc_ln83_reg_479 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_24_fu_118 <= weight_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln4_reg_475 == 2'd1) & ~(trunc_ln4_reg_475 == 2'd0) & (trunc_ln83_reg_479 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_25_fu_122 <= weight_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln4_reg_475 == 2'd1) & ~(trunc_ln83_reg_479 == 2'd1) & ~(trunc_ln83_reg_479 == 2'd0) & ~(trunc_ln4_reg_475 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_26_fu_126 <= weight_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln83_reg_479 == 2'd0) & (trunc_ln4_reg_475 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_fu_94 <= weight_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln4_reg_475 <= {{ap_sig_allocacmp_phi_mul14_load[7:6]}};
        trunc_ln83_reg_479 <= trunc_ln83_fu_264_p1;
    end
end

always @ (*) begin
    if (((icmp_ln73_fu_233_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_2 = rem_fu_90;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_phi_mul14_load = 8'd0;
    end else begin
        ap_sig_allocacmp_phi_mul14_load = phi_mul14_fu_86;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_phi_urem16_load = 4'd0;
    end else begin
        ap_sig_allocacmp_phi_urem16_load = phi_urem16_fu_82;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln73_fu_233_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln73_fu_233_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out2_ap_vld = 1'b1;
    end else begin
        p_out2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln73_fu_233_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out3_ap_vld = 1'b1;
    end else begin
        p_out3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln73_fu_233_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out4_ap_vld = 1'b1;
    end else begin
        p_out4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln73_fu_233_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out5_ap_vld = 1'b1;
    end else begin
        p_out5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln73_fu_233_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out6_ap_vld = 1'b1;
    end else begin
        p_out6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln73_fu_233_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out7_ap_vld = 1'b1;
    end else begin
        p_out7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln73_fu_233_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out8_ap_vld = 1'b1;
    end else begin
        p_out8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln73_fu_233_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weight_stream_TDATA_blk_n = weight_stream_TVALID;
    end else begin
        weight_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weight_stream_TREADY = 1'b1;
    end else begin
        weight_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln73_1_fu_277_p2 = (ap_sig_allocacmp_phi_urem16_load + 4'd1);

assign add_ln81_fu_248_p2 = (ap_sig_allocacmp_phi_mul14_load + 8'd22);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((weight_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((weight_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((weight_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((weight_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign i_fu_239_p2 = (ap_sig_allocacmp_i_2 + 4'd1);

assign icmp_ln73_1_fu_283_p2 = ((ap_sig_allocacmp_phi_urem16_load == 4'd2) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_233_p2 = ((ap_sig_allocacmp_i_2 == 4'd9) ? 1'b1 : 1'b0);

assign p_out = empty_26_fu_126;

assign p_out1 = empty_25_fu_122;

assign p_out2 = empty_24_fu_118;

assign p_out3 = empty_23_fu_114;

assign p_out4 = empty_22_fu_110;

assign p_out5 = empty_21_fu_106;

assign p_out6 = empty_20_fu_102;

assign p_out7 = empty_19_fu_98;

assign p_out8 = empty_fu_94;

assign select_ln73_fu_289_p3 = ((icmp_ln73_1_fu_283_p2[0:0] == 1'b1) ? 4'd0 : add_ln73_1_fu_277_p2);

assign trunc_ln83_fu_264_p1 = ap_sig_allocacmp_phi_urem16_load[1:0];

endmodule //conv2d_conv2d_Pipeline_READ_WEIGHTS
