// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module conv2d_conv2d_Pipeline_WRITE_OUTPUT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_stream_TREADY,
        output_reload,
        output_1_reload,
        output_2_reload,
        output_3_reload,
        output_4_reload,
        output_5_reload,
        output_6_reload,
        output_7_reload,
        output_8_reload,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   out_stream_TREADY;
input  [15:0] output_reload;
input  [15:0] output_1_reload;
input  [15:0] output_2_reload;
input  [15:0] output_3_reload;
input  [15:0] output_4_reload;
input  [15:0] output_5_reload;
input  [15:0] output_6_reload;
input  [15:0] output_7_reload;
input  [15:0] output_8_reload;
output  [15:0] out_stream_TDATA;
output   out_stream_TVALID;
output  [1:0] out_stream_TKEEP;
output  [1:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;

reg ap_idle;
reg out_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln109_fu_194_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    out_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire   [15:0] p_0_fu_312_p9;
reg   [15:0] p_0_reg_377;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln118_fu_332_p2;
reg   [0:0] icmp_ln118_reg_382;
reg   [3:0] phi_urem24_fu_92;
wire   [3:0] select_ln110_fu_224_p3;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_phi_urem24_load;
wire    ap_block_pp0_stage0;
reg   [7:0] phi_mul22_fu_96;
wire   [7:0] add_ln113_fu_232_p2;
reg   [7:0] ap_sig_allocacmp_phi_mul22_load;
reg   [3:0] rem_fu_100;
wire   [3:0] i_fu_200_p2;
reg   [3:0] ap_sig_allocacmp_i_1;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [0:0] icmp_ln110_fu_218_p2;
wire   [3:0] add_ln110_fu_212_p2;
wire   [15:0] tmp_fu_252_p7;
wire   [1:0] trunc_ln116_fu_248_p1;
wire   [15:0] tmp_1_fu_272_p7;
wire   [15:0] tmp_2_fu_292_p7;
wire   [15:0] tmp_fu_252_p9;
wire   [15:0] tmp_1_fu_272_p9;
wire   [15:0] tmp_2_fu_292_p9;
wire   [15:0] p_0_fu_312_p7;
wire   [1:0] p_0_fu_312_p8;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] tmp_fu_252_p1;
wire   [1:0] tmp_fu_252_p3;
wire  signed [1:0] tmp_fu_252_p5;
wire   [1:0] tmp_1_fu_272_p1;
wire   [1:0] tmp_1_fu_272_p3;
wire  signed [1:0] tmp_1_fu_272_p5;
wire   [1:0] tmp_2_fu_292_p1;
wire   [1:0] tmp_2_fu_292_p3;
wire  signed [1:0] tmp_2_fu_292_p5;
wire   [1:0] p_0_fu_312_p1;
wire   [1:0] p_0_fu_312_p3;
wire  signed [1:0] p_0_fu_312_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 phi_urem24_fu_92 = 4'd0;
#0 phi_mul22_fu_96 = 8'd0;
#0 rem_fu_100 = 4'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) conv2d_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U122(
    .din0(output_reload),
    .din1(output_1_reload),
    .din2(output_2_reload),
    .def(tmp_fu_252_p7),
    .sel(trunc_ln116_fu_248_p1),
    .dout(tmp_fu_252_p9)
);

(* dissolve_hierarchy = "yes" *) conv2d_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U123(
    .din0(output_3_reload),
    .din1(output_4_reload),
    .din2(output_5_reload),
    .def(tmp_1_fu_272_p7),
    .sel(trunc_ln116_fu_248_p1),
    .dout(tmp_1_fu_272_p9)
);

(* dissolve_hierarchy = "yes" *) conv2d_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U124(
    .din0(output_6_reload),
    .din1(output_7_reload),
    .din2(output_8_reload),
    .def(tmp_2_fu_292_p7),
    .sel(trunc_ln116_fu_248_p1),
    .dout(tmp_2_fu_292_p9)
);

(* dissolve_hierarchy = "yes" *) conv2d_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U125(
    .din0(tmp_fu_252_p9),
    .din1(tmp_1_fu_272_p9),
    .din2(tmp_2_fu_292_p9),
    .def(p_0_fu_312_p7),
    .sel(p_0_fu_312_p8),
    .dout(p_0_fu_312_p9)
);

conv2d_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln109_fu_194_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            phi_mul22_fu_96 <= add_ln113_fu_232_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_mul22_fu_96 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln109_fu_194_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            phi_urem24_fu_92 <= select_ln110_fu_224_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_urem24_fu_92 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln109_fu_194_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            rem_fu_100 <= i_fu_200_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            rem_fu_100 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln118_reg_382 <= icmp_ln118_fu_332_p2;
        p_0_reg_377 <= p_0_fu_312_p9;
    end
end

always @ (*) begin
    if (((icmp_ln109_fu_194_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_1 = rem_fu_100;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_phi_mul22_load = 8'd0;
    end else begin
        ap_sig_allocacmp_phi_mul22_load = phi_mul22_fu_96;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_phi_urem24_load = 4'd0;
    end else begin
        ap_sig_allocacmp_phi_urem24_load = phi_urem24_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_stream_TVALID = 1'b1;
    end else begin
        out_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln110_fu_212_p2 = (ap_sig_allocacmp_phi_urem24_load + 4'd1);

assign add_ln113_fu_232_p2 = (ap_sig_allocacmp_phi_mul22_load + 8'd22);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign i_fu_200_p2 = (ap_sig_allocacmp_i_1 + 4'd1);

assign icmp_ln109_fu_194_p2 = ((ap_sig_allocacmp_i_1 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln110_fu_218_p2 = ((ap_sig_allocacmp_phi_urem24_load == 4'd2) ? 1'b1 : 1'b0);

assign icmp_ln118_fu_332_p2 = ((ap_sig_allocacmp_i_1 == 4'd8) ? 1'b1 : 1'b0);

assign out_stream_TDATA = p_0_reg_377;

assign out_stream_TKEEP = 2'd3;

assign out_stream_TLAST = icmp_ln118_reg_382;

assign out_stream_TSTRB = 2'd3;

assign p_0_fu_312_p7 = 'bx;

assign p_0_fu_312_p8 = {{ap_sig_allocacmp_phi_mul22_load[7:6]}};

assign select_ln110_fu_224_p3 = ((icmp_ln110_fu_218_p2[0:0] == 1'b1) ? 4'd0 : add_ln110_fu_212_p2);

assign tmp_1_fu_272_p7 = 'bx;

assign tmp_2_fu_292_p7 = 'bx;

assign tmp_fu_252_p7 = 'bx;

assign trunc_ln116_fu_248_p1 = ap_sig_allocacmp_phi_urem24_load[1:0];

endmodule //conv2d_conv2d_Pipeline_WRITE_OUTPUT
