

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "3", "5", "40", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57"],
		"CDFG" : "conv2d",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "66", "EstimateLatencyMax" : "66",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "in_stream_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_stream",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv2d_Pipeline_READ_INPUT_fu_252", "Port" : "in_stream_V_data_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "in_stream_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_stream",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv2d_Pipeline_READ_INPUT_fu_252", "Port" : "in_stream_V_keep_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "in_stream_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_stream",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv2d_Pipeline_READ_INPUT_fu_252", "Port" : "in_stream_V_strb_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "in_stream_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_stream",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv2d_Pipeline_READ_INPUT_fu_252", "Port" : "in_stream_V_last_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "weight_stream_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "weight_stream",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_conv2d_Pipeline_READ_WEIGHTS_fu_289", "Port" : "weight_stream_V_data_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "weight_stream_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "weight_stream",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_conv2d_Pipeline_READ_WEIGHTS_fu_289", "Port" : "weight_stream_V_keep_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "weight_stream_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "weight_stream",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_conv2d_Pipeline_READ_WEIGHTS_fu_289", "Port" : "weight_stream_V_strb_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "weight_stream_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "weight_stream",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_conv2d_Pipeline_READ_WEIGHTS_fu_289", "Port" : "weight_stream_V_last_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "bias", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_stream_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358", "Port" : "out_stream_V_data_V", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "out_stream_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358", "Port" : "out_stream_V_keep_V", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "out_stream_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358", "Port" : "out_stream_V_strb_V", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "out_stream_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358", "Port" : "out_stream_V_last_V", "Inst_start_state" : "6", "Inst_end_state" : "7"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_READ_INPUT_fu_252", "Parent" : "0", "Child" : ["2"],
		"CDFG" : "conv2d_Pipeline_READ_INPUT",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "27", "EstimateLatencyMax" : "27",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "in_stream_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_stream",
				"BlockSignal" : [
					{"Name" : "in_stream_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "in_stream_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_stream"},
			{"Name" : "in_stream_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_stream"},
			{"Name" : "in_stream_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_stream"},
			{"Name" : "input_24_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_23_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_22_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_21_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_20_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_19_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_18_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_17_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_16_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_15_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_14_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_13_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_12_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_11_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_10_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_9_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_8_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_7_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_6_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_5_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_3_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "READ_INPUT", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_READ_INPUT_fu_252.flow_control_loop_pipe_sequential_init_U", "Parent" : "1"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_READ_WEIGHTS_fu_289", "Parent" : "0", "Child" : ["4"],
		"CDFG" : "conv2d_Pipeline_READ_WEIGHTS",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "11", "EstimateLatencyMax" : "11",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "weight_stream_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "weight_stream",
				"BlockSignal" : [
					{"Name" : "weight_stream_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "weight_stream_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "weight_stream"},
			{"Name" : "weight_stream_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "weight_stream"},
			{"Name" : "weight_stream_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "weight_stream"},
			{"Name" : "p_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out1", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out2", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out3", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out4", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out5", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out6", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out7", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out8", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "READ_WEIGHTS", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_READ_WEIGHTS_fu_289.flow_control_loop_pipe_sequential_init_U", "Parent" : "3"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310", "Parent" : "0", "Child" : ["6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39"],
		"CDFG" : "conv2d_Pipeline_CONV_OR_CONV_OC2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "21", "EstimateLatencyMax" : "21",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_1_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_2_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_5_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_6_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_7_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_10_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_11_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_12_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln96", "Type" : "None", "Direction" : "I"},
			{"Name" : "shl_ln", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_3_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_8_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_13_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln96_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_4_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_9_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_14_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln96_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_15_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_16_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_17_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln96_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_18_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln96_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_19_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln96_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_20_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_21_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_22_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln96_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_23_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln96_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_24_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln96_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_8_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_7_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_6_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_5_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_3_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "CONV_OR_CONV_OC2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter11", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter11", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U43", "Parent" : "5"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U44", "Parent" : "5"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U45", "Parent" : "5"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U46", "Parent" : "5"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U47", "Parent" : "5"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U48", "Parent" : "5"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U49", "Parent" : "5"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U50", "Parent" : "5"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U51", "Parent" : "5"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U52", "Parent" : "5"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U53", "Parent" : "5"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U54", "Parent" : "5"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U55", "Parent" : "5"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U56", "Parent" : "5"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U57", "Parent" : "5"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U58", "Parent" : "5"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U59", "Parent" : "5"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U60", "Parent" : "5"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U61", "Parent" : "5"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U62", "Parent" : "5"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U63", "Parent" : "5"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U64", "Parent" : "5"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U65", "Parent" : "5"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.sparsemux_7_2_16_1_1_U66", "Parent" : "5"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.mac_muladd_16s_16s_24s_24_4_1_U67", "Parent" : "5"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.mac_muladd_16s_16s_24s_24_4_1_U68", "Parent" : "5"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.mac_muladd_16s_16s_24s_24_4_1_U69", "Parent" : "5"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.mac_muladd_16s_16s_24s_24_4_1_U70", "Parent" : "5"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.mac_muladd_16s_16s_24s_24_4_1_U71", "Parent" : "5"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.mac_muladd_16s_16s_24s_24_4_1_U72", "Parent" : "5"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.mac_muladd_16s_16s_24s_24_4_1_U73", "Parent" : "5"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.mac_muladd_16s_16s_24s_24_4_1_U74", "Parent" : "5"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.mac_muladd_16s_16s_24s_24_4_1_U75", "Parent" : "5"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_CONV_OR_CONV_OC2_fu_310.flow_control_loop_pipe_sequential_init_U", "Parent" : "5"},
	{"ID" : "40", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358", "Parent" : "0", "Child" : ["41", "42", "43", "44", "45"],
		"CDFG" : "conv2d_Pipeline_WRITE_OUTPUT",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "11", "EstimateLatencyMax" : "11",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "output_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_1_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_2_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_3_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_4_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_5_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_6_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_7_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_8_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_stream_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"BlockSignal" : [
					{"Name" : "out_stream_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "out_stream_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream"},
			{"Name" : "out_stream_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream"},
			{"Name" : "out_stream_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream"}],
		"Loop" : [
			{"Name" : "WRITE_OUTPUT", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358.sparsemux_7_2_16_1_1_U122", "Parent" : "40"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358.sparsemux_7_2_16_1_1_U123", "Parent" : "40"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358.sparsemux_7_2_16_1_1_U124", "Parent" : "40"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358.sparsemux_7_2_16_1_1_U125", "Parent" : "40"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2d_Pipeline_WRITE_OUTPUT_fu_358.flow_control_loop_pipe_sequential_init_U", "Parent" : "40"},
	{"ID" : "46", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_data_V_U", "Parent" : "0"},
	{"ID" : "47", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_keep_V_U", "Parent" : "0"},
	{"ID" : "48", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_strb_V_U", "Parent" : "0"},
	{"ID" : "49", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_last_V_U", "Parent" : "0"},
	{"ID" : "50", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_weight_stream_V_data_V_U", "Parent" : "0"},
	{"ID" : "51", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_weight_stream_V_keep_V_U", "Parent" : "0"},
	{"ID" : "52", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_weight_stream_V_strb_V_U", "Parent" : "0"},
	{"ID" : "53", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_weight_stream_V_last_V_U", "Parent" : "0"},
	{"ID" : "54", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_data_V_U", "Parent" : "0"},
	{"ID" : "55", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_keep_V_U", "Parent" : "0"},
	{"ID" : "56", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_strb_V_U", "Parent" : "0"},
	{"ID" : "57", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_last_V_U", "Parent" : "0"}]}
